### ISSUE TITLE
Cannot compile with pyotrch 0.4.1

### ISSUE THREAD

**Issue by shaibagon** [chrischoy/pytorch_knn_cuda#3]
Getting error
```
gcc -pthread -B /home/bagon/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/bagon/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/bagon/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/bagon/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/bagon/anaconda3/pkgs/pytorch_knn_cuda/include -I/home/bagon/anaconda3/include/python3.6m -c /home/bagon/anaconda3/pkgs/pytorch_knn_cuda/src/knn_pytorch.c -o ./home/bagon/anaconda3/pkgs/pytorch_knn_cuda/src/knn_pytorch.o -std=c99
In file included from /home/bagon/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:4:0,
                 from /home/bagon/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4,
                 from /home/bagon/anaconda3/pkgs/pytorch_knn_cuda/src/knn_pytorch.c:1:
/home/bagon/anaconda3/pkgs/pytorch_knn_cuda/src/knn_pytorch.c: In function ‘knn’:
/home/bagon/anaconda3/pkgs/pytorch_knn_cuda/src/knn_pytorch.c:11:24: error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’
   THArgCheck(ref_tensor->nDimension == 2 , 0, "ref_tensor: 2D Tensor expected");
                        ^
/home/bagon/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:111:35: note: in definition of macro ‘THArgCheck’
   _THArgCheck(__FILE__, __LINE__, __VA_ARGS__);
```
It seems like the definition of `struct THTensor` was moved from `THTensor.h` to `THTensor.hpp` and this  causes this issue.

Any way to workaround this?
